FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY frontend/package*.json ./
RUN npm ci

COPY frontend .

RUN npm run build

FROM nginx:1.27-alpine

RUN apk add --no-cache python3

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist/frontend/browser/ /usr/share/nginx/html/
COPY frontend/docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
