FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY frontend/package*.json ./
RUN npm ci

COPY frontend .

RUN npm run build

FROM nginx:1.27-alpine

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist/frontend /usr/share/nginx/html

EXPOSE 80
